// Real NUS SEP partner universities — used as fallback when the DB is empty
export const STATIC_PARTNERS = [
  // Asia Pacific
  { id: "static-umelb", name: "University of Melbourne", country: "Australia", region: "Oceania" },
  { id: "static-usyd", name: "University of Sydney", country: "Australia", region: "Oceania" },
  { id: "static-anu", name: "Australian National University", country: "Australia", region: "Oceania" },
  { id: "static-uq", name: "University of Queensland", country: "Australia", region: "Oceania" },
  { id: "static-unsw", name: "UNSW Sydney", country: "Australia", region: "Oceania" },
  { id: "static-hku", name: "University of Hong Kong", country: "Hong Kong", region: "Asia Pacific" },
  { id: "static-cuhk", name: "Chinese University of Hong Kong", country: "Hong Kong", region: "Asia Pacific" },
  { id: "static-hkust", name: "Hong Kong University of Science and Technology", country: "Hong Kong", region: "Asia Pacific" },
  { id: "static-pku", name: "Peking University", country: "China", region: "Asia Pacific" },
  { id: "static-tsinghua", name: "Tsinghua University", country: "China", region: "Asia Pacific" },
  { id: "static-fudan", name: "Fudan University", country: "China", region: "Asia Pacific" },
  { id: "static-zju", name: "Zhejiang University", country: "China", region: "Asia Pacific" },
  { id: "static-utokyo", name: "University of Tokyo", country: "Japan", region: "Asia Pacific" },
  { id: "static-kyoto", name: "Kyoto University", country: "Japan", region: "Asia Pacific" },
  { id: "static-waseda", name: "Waseda University", country: "Japan", region: "Asia Pacific" },
  { id: "static-keio", name: "Keio University", country: "Japan", region: "Asia Pacific" },
  { id: "static-osaka", name: "Osaka University", country: "Japan", region: "Asia Pacific" },
  { id: "static-snu", name: "Seoul National University", country: "South Korea", region: "Asia Pacific" },
  { id: "static-kaist", name: "Korea Advanced Institute of Science and Technology", country: "South Korea", region: "Asia Pacific" },
  { id: "static-yonsei", name: "Yonsei University", country: "South Korea", region: "Asia Pacific" },
  { id: "static-ntu-taiwan", name: "National Taiwan University", country: "Taiwan", region: "Asia Pacific" },
  { id: "static-iitb", name: "Indian Institute of Technology Bombay", country: "India", region: "Asia Pacific" },
  // Europe
  { id: "static-ethz", name: "ETH Zurich", country: "Switzerland", region: "Europe" },
  { id: "static-epfl", name: "EPFL", country: "Switzerland", region: "Europe" },
  { id: "static-tum", name: "Technical University of Munich", country: "Germany", region: "Europe" },
  { id: "static-lmu", name: "LMU Munich", country: "Germany", region: "Europe" },
  { id: "static-rwth", name: "RWTH Aachen University", country: "Germany", region: "Europe" },
  { id: "static-icl", name: "Imperial College London", country: "United Kingdom", region: "Europe" },
  { id: "static-ucl", name: "University College London", country: "United Kingdom", region: "Europe" },
  { id: "static-edinburgh", name: "University of Edinburgh", country: "United Kingdom", region: "Europe" },
  { id: "static-manchester", name: "University of Manchester", country: "United Kingdom", region: "Europe" },
  { id: "static-kingscollegelondon", name: "King's College London", country: "United Kingdom", region: "Europe" },
  { id: "static-sciencespo", name: "Sciences Po", country: "France", region: "Europe" },
  { id: "static-essec", name: "ESSEC Business School", country: "France", region: "Europe" },
  { id: "static-hec", name: "HEC Paris", country: "France", region: "Europe" },
  { id: "static-uva", name: "University of Amsterdam", country: "Netherlands", region: "Europe" },
  { id: "static-tudelft", name: "Delft University of Technology", country: "Netherlands", region: "Europe" },
  { id: "static-erasmus", name: "Erasmus University Rotterdam", country: "Netherlands", region: "Europe" },
  { id: "static-kth", name: "KTH Royal Institute of Technology", country: "Sweden", region: "Europe" },
  { id: "static-cbs", name: "Copenhagen Business School", country: "Denmark", region: "Europe" },
  { id: "static-ucph", name: "University of Copenhagen", country: "Denmark", region: "Europe" },
  { id: "static-bocconi", name: "Bocconi University", country: "Italy", region: "Europe" },
  { id: "static-aalto", name: "Aalto University", country: "Finland", region: "Europe" },
  { id: "static-uu", name: "Uppsala University", country: "Sweden", region: "Europe" },
  // Americas
  { id: "static-ubc", name: "University of British Columbia", country: "Canada", region: "Americas" },
  { id: "static-utoronto", name: "University of Toronto", country: "Canada", region: "Americas" },
  { id: "static-mcgill", name: "McGill University", country: "Canada", region: "Americas" },
  { id: "static-ucb", name: "UC Berkeley", country: "United States", region: "Americas" },
  { id: "static-ucla", name: "UCLA", country: "United States", region: "Americas" },
  { id: "static-cmu", name: "Carnegie Mellon University", country: "United States", region: "Americas" },
  { id: "static-umich", name: "University of Michigan", country: "United States", region: "Americas" },
  { id: "static-gatech", name: "Georgia Institute of Technology", country: "United States", region: "Americas" },
  { id: "static-uiuc", name: "University of Illinois Urbana-Champaign", country: "United States", region: "Americas" },
  { id: "static-purdue", name: "Purdue University", country: "United States", region: "Americas" },
  { id: "static-usc", name: "University of Southern California", country: "United States", region: "Americas" },
  { id: "static-bu", name: "Boston University", country: "United States", region: "Americas" },
  // Middle East & Africa
  { id: "static-technion", name: "Technion – Israel Institute of Technology", country: "Israel", region: "Middle East & Africa" },
  { id: "static-tau", name: "Tel Aviv University", country: "Israel", region: "Middle East & Africa" },
  { id: "static-huji", name: "Hebrew University of Jerusalem", country: "Israel", region: "Middle East & Africa" },
].map((p) => ({ ...p, _count: { overseasCourses: 0 } }));
